### ISSUE TITLE
Ask a few questions about using qemu-user-static 

### ISSUE THREAD

**Issue by xinfeingxia85** [nalind/fedora-qemu-user-static#1]
### **Describe some situations** 

I am planning to replace the `docker buildx` with `buildah`, and the qemu-user-static is installed to build multi-arch images on the AWS EKS using Bottlerocket OS. 

But the qemu-user-static must enable the privileged mode when running in the container by the Gitlab runner.  To limit the number of privileged containers,  the qemu-user-static will be deployed with DaemonSet.  

It can be done only according to the way you provided. It was deployed using the  `multiarch/qemu-user-static` image, but it failed to emulate the no-native architecture in the other pods. 

I‘v read the code,  and I‘d like to ask some technical questions , which I'm confused about. 

Thank you for you help.

### **Ask these questions**

1. DaemonSet yaml with the image `ghcr.io/nalind/fedora-qemu-user-static` 
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: qemu-user-static
spec:
  selector:
    matchLabels:
      name: qemu-user-static
  template:
    metadata:
      labels:
        name: qemu-user-static
    spec:
      volumes:
      - name: hostbindir # a directory on the host which won't persist
        hostPath:
          path: /run/qemu-user-static
      initContainers:
      - name: qemu-user-static
        image: ghcr.io/nalind/fedora-qemu-user-static:2022-06-12
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: hostbindir # mount that non-persistent directory into the container so that we can copy interpreters into it
          mountPath: /usr/local/bin
        securityContext:
          privileged: true
        env:
        - name: BINDIR # entrypoint.sh will copy interpreters to this directory in the container
          value: /usr/local/bin
        # - name: CHCON # entrypoint.sh will run "chcon" with this as its argument for each interpreter after copying
        #   value: -t bin_t
        command:
        - /bin/sh
        - -c 
        - |
          /entrypoint.sh register

          while true
          do
            sleep 1
          done
      containers:
      - image: k8s.gcr.io/pause:3.2
        name: pause
      nodeSelector:
        kubernetes.io/os: linux
```
I must set the environment `BINDIR` and volumes `hostbindir`,  otherwise  it doesn't work fine.
The errors are ：
```
[linux/arm64] STEP 2/2: RUN apt-get update -y   && apt-get -y install bc
subprocess exited on segmentation fault
subprocess exited with status 1
``` 
I want to know the reason why  the binaries must be reinstalled to work fine in other containers.

2. DaemonSet yaml with the image `multiarch/qemu-user-static` 
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: qemu-user-static
spec:
  selector:
    matchLabels:
      name: qemu-user-static
  template:
    metadata:
      labels:
        name: qemu-user-static
    spec:
      containers:
      - name: qemu-user-static
        image: multiarch/qemu-user-static
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command:
        - /bin/sh
        - -c 
        - |
          /register --reset -p yes
          while true
          do
            sleep 1
          done
```
I deployed it with the yaml above, but it could not work fine.  In the container,  it failed to build the multi-arch image.

3. The latest image `ghcr.io/nalind/fedora-qemu-user-static:2022-06-16` alway failed to be pulled.
     The error is as follows:
  ```
 Normal   Scheduled  14s   default-scheduler  Successfully assigned default/qemu-user-static-7868dd7775-v8b2t to ip-10-0-2-27.us-east-2.compute.internal
  Normal   Pulling    14s   kubelet            Pulling image "ghcr.io/nalind/fedora-qemu-user-static"
  Warning  Failed     11s   kubelet            Failed to pull image "ghcr.io/nalind/fedora-qemu-user-static": rpc error: code = Unknown desc = failed to pull and unpack image "ghcr.io/nalind/fedora-qemu-user-static:latest": failed to extract layer sha256:65bd9874ff899efc3d741051a8034a1a042e6e7f25bb543e91aa6a29c014a80b: operation not permitted: unknown
  Warning  Failed     11s   kubelet            Error: ErrImagePull
  Normal   BackOff    10s   kubelet            Back-off pulling image "ghcr.io/nalind/fedora-qemu-user-static"
  Warning  Failed     10s   kubelet            Error: ImagePullBackOff
 ```
